[project]
name = "poc-excel"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chardet>=5.2.0",
    "langchain-groq>=1.0.0",
    "langfuse>=2.60.10",
    "protobuf==3.20.0",
]
